version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    expose:
      - '9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1\
    restart: on-failure

  init-kafka:
    image: confluentinc/cp-kafka
    depends_on:
      - kafka
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      # blocks until kafka is reachable
      kafka-topics --bootstrap-server kafka:29092 --list

      echo -e 'Creating kafka topics'
      kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic iot-data-event --replication-factor 1 --partitions 1
      kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic sensor-update-event --replication-factor 1 --partitions 1
      kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic processed-data-event --replication-factor 1 --partitions 1

      echo -e 'Successfully created the following topics:'
      kafka-topics --bootstrap-server kafka:9092 --list
      "
  eureka:
    image: thebestsmartfarm/smart-farm-eureka
    ports:
      - 8761:8761

  sensor-data-producer:
    image: thebestsmartfarm/sensor-data-producer-service
    depends_on:
      - zookeeper
      - kafka
      - init-kafka
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    restart: on-failure

  farm-data-service:
    image: thebestsmartfarm/farm-data-service
    ports:
      - 8081:8081
    depends_on:
      - zookeeper
      - kafka
      - init-kafka
      - eureka
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka/
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
      SPRING_CLOUD_DISCOVERY_ENABLED: 'true'
    restart: on-failure

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    ports:
      - 27017:27017

  redis:
    image: 'redis'
    container_name: redis
    hostname: redis
    ports:
      - 6379:6379

  sensor-data-processor:
    image: thebestsmartfarm/sensor-data-service
    depends_on:
      - zookeeper
      - kafka
      - init-kafka
      - eureka
      - sensor-data-producer
      - mongodb
      - redis
      - farm-data-service
    links:
      - mongodb
      - redis
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_DATA_MONGODB_URI: mongodb://host.docker.internal:27017/sensordata
      SMART_FARM_FARMDATA_SERVICE_HOST: http://gateway:9090/farm-data-service
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka/
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
      SPRING_CLOUD_DISCOVERY_ENABLED: 'true'
    restart: on-failure

  controller-management-service:
    image: thebestsmartfarm/controller-management-service
    depends_on:
      - zookeeper
      - kafka
      - init-kafka
      - sensor-data-processor
      - eureka
      - notification-service
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka/
      SMART_FARM_NOTIFICATION_SERVICE_HOST: http://gateway:9090/notification-service
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
      SPRING_CLOUD_DISCOVERY_ENABLED: 'true'
    restart: on-failure

  notification-service:
    image: thebestsmartfarm/notification-service
    ports:
      - 8083:8083
    depends_on:
      - eureka
    environment:
      BOT_NAME: '@SmartFarmNotificationsBot'
      BOT_TOKEN: '5898076220:AAFBUSphclzUq1qcizhCmJWf1O3HQiU0FIY'
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka/
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
      SPRING_CLOUD_DISCOVERY_ENABLED: 'true'
    restart: on-failure

  gateway:
    image: thebestsmartfarm/smart-farm-gateway
    ports:
      - 9090:9090
    depends_on:
      - eureka
      - farm-data-service
      - sensor-data-processor
      - controller-management-service
      - notification-service
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka/
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
    restart: on-failure